# Define os serviços que compõem a pilha da aplicação WordPress.
services:

  # Serviço configurado para expor a porta 8080 do host e encaminhar o tráfego para a aplicação principal.
  webproxy:
    image: jaocalheiros/nginx-custom:latest
    container_name: webproxy

    ports:
      - "8080:8080"

    networks:
      - wordpress

    depends_on:
      - webserver

  # Servidor WordPress que usa o MySQL como backend e mantém os arquivos da aplicação em um volume persistente.
  webserver:
    image: wordpress:latest
    container_name: webserver

    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress123
      WORDPRESS_DB_NAME: wordpress

    volumes:
      - app:/var/www/html

    networks:
      - wordpress

    depends_on:
      - database

  # Banco de dados MySQL que armazena o conteúdo do WordPress com credenciais definidas para o ambiente.
  database:
    image: mysql:latest
    container_name: database

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress123

    volumes:
      - my:/var/lib/mysql

    networks:
      - wordpress

# Define volumes nomeados para preservar os dados do WordPress e do banco entre reinicializações.
volumes:
  app:
  my:

# Cria uma rede interna isolada para permitir a comunicação entre os containers da stack.
networks:
  wordpress:
