version: '3.8'

networks:
  wordpress:
    driver: bridge

volumes:
  app:
  my:

services:
  webproxy:
    image: seu-usuario-dockerhub/nginx-custom:latest # Substitua pelo seu repositório do Docker Hub
    container_name: webproxy
    ports:
      - "8080:8080"
    networks:
      - wordpress
    depends_on:
      - webserver

  webserver:
    image: wordpress:latest
    container_name: webserver
    restart: always
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - app:/var/www/html
    networks:
      - wordpress
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - my:/var/lib/mysql
    networks:
      - wordpress
