---
- name: Provisionamento Docker Wordpress
  hosts: all
  become: true

  tasks:

    - name: Atualizar cache do apt
      apt:
        update_cache: yes

    - name: Atualizar sistema
      apt:
        upgrade: dist

    - name: Instalar Docker
      apt:
        name:
          - docker.io
          - docker-compose
        update_cache: yes
        state: present

    - name: Habilitar Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Criar diretorio da aplicacao
      file:
        path: /opt/wordpress
        state: directory

    - name: Copiar docker-compose
      copy:
        src: docker-compose.yml
        dest: /opt/wordpress/docker-compose.yml

    - name: Executar Docker Compose
      command: docker-compose up -d
      args:
        chdir: /opt/wordpress
